#By Urolime Technologies
version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./wordpress/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: intraweb/wordpress-nginx:v1
     volumes:
       - "./wordpress/nginx:/usr/share/nginx/html"
       - "./wordpress/system-config:/usr/share/nginx/system-config"
     restart: always
     links:
       - db
     ports:
       - "80:80"
       - "443:443"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
